### ISSUE TITLE
bug(cli): Make develop command doesn't start monetr-ui container.

### ISSUE THREAD

**Issue by abiodunjames** [monetr/monetr#1681]
I tried to run the application. I couldn't start monetr-ui which remains unhealthy.
A quick look at the logs shows that `rspack/binding-linux-arm64-gnu` dependency is missing and couldn't install during the build stage.

```
Node.js v18.10.0
 ELIFECYCLE  Command failed with exit code 1.
[ui] pnpm is already installed, skipping...

> @monetr/interface@0.1.0 start /build/interface
> MONETR_ENV=${MONETR_ENV:=local} rspack serve --mode development

/build/node_modules/@rspack/binding/binding.js:217
    throw loadError
    ^

Error: Cannot find module '@rspack/binding-linux-arm64-gnu'
Require stack:
- /build/node_modules/@rspack/binding/binding.js
```

**Comment by elliotcourant** [comment]
Oh I think I see the problem sorry about that, we have the x86 binding pinned but not the arm64 one. So if you are running on an M1 Mac or something it will have the problem you're having. If you want to add the arm64 binding to the interface/package.json go for it! Otherwise I can have a fix up later today!

Thank you!
